-- 014_create_loans_table.sql
-- Creates the loans table to track asset checkouts and check-ins.

CREATE TABLE public.loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id UUID NOT NULL REFERENCES public.assets(asset_tag) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES public.employees(id) ON DELETE RESTRICT,
    checkout_date TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    expected_return_date TIMESTAMPTZ NOT NULL,
    actual_return_date TIMESTAMPTZ,
    status TEXT NOT NULL CHECK (status IN ('checked_out', 'returned', 'overdue')),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update the updated_at column on every update
CREATE TRIGGER on_loans_update
BEFORE UPDATE ON public.loans
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Indexes for faster queries
CREATE INDEX idx_loans_asset_id ON public.loans(asset_id);
CREATE INDEX idx_loans_employee_id ON public.loans(employee_id);
CREATE INDEX idx_loans_status ON public.loans(status);

-- Enable Row Level Security
ALTER TABLE public.loans ENABLE ROW LEVEL SECURITY;

-- RLS Policies for loans table

-- Allow authenticated users to view loans.
-- Users can see their own loans.
-- Admins/IT staff can see all loans.
CREATE POLICY "Allow authenticated users to read loans"
ON public.loans
FOR SELECT
TO authenticated
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
  OR
  (employee_id = (SELECT id FROM public.employees WHERE email = auth.email()))
);

-- Allow users to be assigned to a loan (implicitly through checkout)
-- and to return their own loans.
-- For now, we will restrict INSERT and UPDATE to admin/it_staff.
CREATE POLICY "Allow admin/it_staff to manage loans"
ON public.loans
FOR ALL
TO authenticated
USING (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
)
WITH CHECK (
  (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('admin', 'it_staff')
);
