create table
  public.activities (
    id bigint primary key generated by default as identity,
    created_at timestamp with time zone not null default now(),
    type text not null,
    description text,
    user_id uuid references auth.users (id),
    asset_id uuid references public.assets (asset_tag) on delete cascade,
    details jsonb
  );

alter table public.activities enable row level security;

create policy "Authenticated users can view activities" on public.activities for
select
  to authenticated using (true);

create policy "Service role can insert activities" on public.activities for insert
to service_role with check (true);
