-- Create maintenance table
CREATE TABLE IF NOT EXISTS public.maintenance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_tag TEXT NOT NULL REFERENCES public.assets(asset_tag) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    cost NUMERIC DEFAULT 0,
    maintenance_date DATE NOT NULL DEFAULT CURRENT_DATE,
    performed_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.maintenance ENABLE ROW LEVEL SECURITY;

-- Add RLS policies
CREATE POLICY "Enable read access for authenticated users" ON public.maintenance
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert access for authenticated users" ON public.maintenance
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update access for authenticated users" ON public.maintenance
    FOR UPDATE USING (auth.role() = 'authenticated');

-- Create index for faster joins
CREATE INDEX IF NOT EXISTS idx_maintenance_asset_tag ON public.maintenance(asset_tag);
