-- Create asset_attachments table
CREATE TABLE IF NOT EXISTS public.asset_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_tag TEXT NOT NULL REFERENCES public.assets(asset_tag) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    file_type TEXT NOT NULL,
    document_type TEXT NOT NULL,
    uploaded_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.asset_attachments ENABLE ROW LEVEL SECURITY;

-- Add RLS policies
CREATE POLICY "Enable read access for authenticated users" ON public.asset_attachments
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert access for authenticated users" ON public.asset_attachments
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable delete access for authenticated users" ON public.asset_attachments
    FOR DELETE USING (auth.role() = 'authenticated');

-- Create index for faster joins
CREATE INDEX IF NOT EXISTS idx_asset_attachments_asset_tag ON public.asset_attachments(asset_tag);

-- Create storage bucket for asset attachments
-- Note: This is a fallback script. In a real environment, you might use the Supabase UI or API to create the bucket.
-- Here we assume the bucket 'asset_attachments' exists or will be created.
INSERT INTO storage.buckets (id, name, public) 
VALUES ('asset_attachments', 'asset_attachments', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for the bucket
CREATE POLICY "Authenticated users can upload attachments" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (bucket_id = 'asset_attachments');

CREATE POLICY "Authenticated users can view attachments" ON storage.objects
    FOR SELECT TO authenticated USING (bucket_id = 'asset_attachments');

CREATE POLICY "Authenticated users can delete their own attachments" ON storage.objects
    FOR DELETE TO authenticated USING (bucket_id = 'asset_attachments');
